Zadania z trzeciego zjazdu
t0meck-pj/sop2022-23_26c pull request #40
Opened 2023-04-21 23:13 UTC by s27085

2023-05-05 21:41 UTC, t0meck-pj requested changes
Prosze poprawic bledy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia2/zadanie5a.txt
> +	będę podmieniał literę 'ę'
Ciekawe polecenie. Ja go nie znam. Bash takze.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia2/zadanie5b.txt
> + ćwiczę referencje do zmiennych
Takze ciekawe niezname mnie i bashowi polecenie.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia2/zadanie6.txt
> +czy imię kończy się na 'ek'; jeżeli tak, to koniec podmieniamy na "ka"
I jeszcze jedno...

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia3/Ćwiczenie1/zad2.txt
> +  ./"$1"
Wypadalo by sprawdzic czy ten plik istnieje.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia3/Ćwiczenie1/zad4.txt
> +  echo "W katalogu jest więcej niż 5 plików"
Jesli w katlogu beda inne katalogi to wynik bedzie bledny. Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/wskazniki/1.c
> +    unsigned int functionId = atoi(argv[1]);
Wymieszany kod wykonywalny z deklaracja zmiennych. Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/wskazniki/1.c
> +    for(int i = 0; i < elementCount-1; i++) {
Z parametrami `-Wall --ansi --pedantic` to nie przejdzie.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/wskazniki/2.c
> +        arguments[i] =  atoi(argv[3+i]);
Czego nie zrobiles wczesniej? Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/wskazniki/2.c
> +    return 0;
Czego nie zrobiles wczesniej? Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/zadaniaOI1/1.c
> +            fscanf(fileToRead, "%d", &numbers[i]);
Czego wczesniej nie zrobiles? Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/zadaniaOI1/1.c
> +            fscanf(stdin, "%d", &numbers[i]);
Czego wczesniej nie zrobiles? Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/zadanieDomowe/listaDwustronna.c
> +    newNode->data = newData;
Czego wczesniej nie zrobiles? Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/zadanieDomowe/listaDwustronna.c
> +    newNode->data = newData;
Czego wczesniej nie zrobiles? Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/zadanieDomowe/listaJednostronna.c
> +    newNode->data=newData;
Czego wczesniej nie zrobiles? Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/zadanieOI2/1.c
> +    charsRead = fread(line, 1, 16, file);
Czego wczesniej nie zrobiles? Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/zadanieOI2/1.c
> +        return -1;
Czego wczesniej nie zrobiles? Do poprawy.

2023-05-05 21:41 UTC, t0meck-pj commented on s27085-KonradFijalkowski/zajecia4/zadanieOI2/1.c
> +    return charsRead;
Czego wczesniej nie zrobiles? Do poprawy.

2023-05-06 18:05 UTC, s27085 commented
naniosłem poprawki, prosiłbym o ich sprawdzenie

2023-05-20 00:17 UTC, merged