Zadania z 4 Zjazdu - C/C++: Wstęp
t0meck-pj/sop2022-23_26c pull request #43
Opened 2023-05-05 21:19 UTC by s27288-pj

2023-05-05 22:19 UTC, t0meck-pj requested changes
Prosze popraw bledy.

2023-05-05 22:19 UTC, t0meck-pj commented on s27288-MateuszLisewski/zajecia4/Zad_1_2.c
> +    while (scanf("%d", &n) == 1 && n != 0) {
To implikuje brak mozliwosci podania liczby zawierajacej powyzej 1 cyfry.

2023-05-05 22:19 UTC, t0meck-pj commented on s27288-MateuszLisewski/zajecia4/Zad_2_OI_1_1.c
> +        fscanf(file, "%d", &num);
Czego wczesniej nie wykonano? Do poprawy.

2023-05-05 22:19 UTC, t0meck-pj commented on s27288-MateuszLisewski/zajecia4/Zad_Dom_1.c
> +    if (temp != NULL && temp->data == value) {
Po co osobno jednorazowo wywolujesz to przed petla?

2023-05-05 22:19 UTC, t0meck-pj commented on s27288-MateuszLisewski/zajecia4/Zad_Dom_1.c
> +    delete(&head, 4);
To nie jest zwalnianie rekurencyjne.
KAZDA dynamicznie zaalokowana pamiec trzeba zwolnic jawnie.

2023-05-05 22:19 UTC, t0meck-pj commented on s27288-MateuszLisewski/zajecia4/Zad_Dom_2.c
> +    deleteAtEnd();
Tworzysz 4 nody. Zwalniasz 2. Do poprawy.

2023-05-05 22:23 UTC, nrabulinski commented on s27288-MateuszLisewski/zajecia4/Zad_1_2.c
> +    while (scanf("%d", &n) == 1 && n != 0) {
To nie jest prawda. Dokumentacja `scanf` mówi jasno:
> RETURN VALUE
> On success, these functions return the number of input items successfully matched and assigned
Czyli 1 tu nie znaczy ilość *znaków* a oznacza ilość *dezygnatorów*, które zostały dopasowane. 
Źródło: https://man7.org/linux/man-pages/man3/scanf.3.html
Inne źródło jeśli nie ufamy tamtemu manualowi: https://linux.die.net/man/3/scanf

2023-05-20 00:48 UTC, t0meck-pj requested changes

2023-05-20 00:48 UTC, t0meck-pj commented on s27288-MateuszLisewski/zajecia4/Zad_Dom_1.c
> +    struct Node* new_node = (struct Node*)malloc(sizeof(struct Node));
Czego nie robisz po tym wierszu?
Do poprawy.

2023-05-20 00:48 UTC, t0meck-pj commented on s27288-MateuszLisewski/zajecia4/Zad_Dom_2.c
> +    Node *newNode = (Node*) malloc(sizeof(Node));
Czego nie robisz po tym wierszu?
Do poprawy.

2023-05-20 00:48 UTC, t0meck-pj commented on s27288-MateuszLisewski/zajecia4/Zad_Dom_2.c
> +    Node *newNode = (Node*) malloc(sizeof(Node));
Czego nie robisz po tym wierszu?
Do poprawy.

2023-06-01 13:15 UTC, s27288-pj commented on s27288-MateuszLisewski/zajecia4/Zad_Dom_1.c
> +    struct Node* new_node = (struct Node*)malloc(sizeof(struct Node));
Poprawione

2023-06-01 13:15 UTC, s27288-pj commented on s27288-MateuszLisewski/zajecia4/Zad_Dom_2.c
> +    Node *newNode = (Node*) malloc(sizeof(Node));
Poprawione

2023-06-01 13:15 UTC, s27288-pj commented on s27288-MateuszLisewski/zajecia4/Zad_Dom_2.c
> +    Node *newNode = (Node*) malloc(sizeof(Node));
Poprawione

2023-06-03 12:53 UTC, t0meck-pj approved these changes

2023-06-03 12:53 UTC, merged