Spotkanie 4 zadania, poprawa formatowania zad.11 spotkanie 3
t0meck-pj/sop2022-23_26c pull request #45
Opened 2023-05-05 21:42 UTC by dawiffi

2023-05-05 22:45 UTC, t0meck-pj requested changes
Prosze poprawic bledy.

2023-05-05 22:45 UTC, t0meck-pj commented on s29608-DawidFrontczak/zajecia3/zadanie11.txt
> +  }
Klamra zamykajaca funkcje powinna byc wyrownana do kolumny w ktorej zaczyna sie kod ja otwierajacy.

2023-05-05 22:45 UTC, t0meck-pj commented on s29608-DawidFrontczak/zajecia4/zadanie2.txt
> +        return 1;
A gdzie zamkniecie pliku?

2023-05-05 22:45 UTC, t0meck-pj commented on s29608-DawidFrontczak/zajecia4/zaddom.txt
> +	n->data = data;
bo `*alloc` zawsze zwroci wskaznik...

2023-05-05 22:45 UTC, t0meck-pj commented on s29608-DawidFrontczak/zajecia4/zaddom.txt
> +	if (temp != NULL && temp->data == data){
Przekombinowane to usuwanie.

2023-05-05 22:45 UTC, t0meck-pj commented on s29608-DawidFrontczak/zajecia4/zaddom.txt
> +    usun(&head, 5);
Tworzysz 5 nodow a usuwasz 2. Korzystasz z dynamicznej alokacji pamieci. Trzeba po sobie posprzatac przed koncem programu.

2023-05-20 00:55 UTC, t0meck-pj requested changes

2023-05-20 00:55 UTC, t0meck-pj commented on s29608-DawidFrontczak/zajecia5/zad2.txt
> +    printf("Proces rodzic\n");
yyy coś nie tak

2023-05-20 00:55 UTC, t0meck-pj commented on s29608-DawidFrontczak/zajecia5/zad2.txt
> +    printf("Proces dziecko\n");
to chyba miało być odwrotnie

2023-05-20 00:55 UTC, t0meck-pj commented on s29608-DawidFrontczak/zajecia5/zad3.txt
> +    wait(0);
I ze zrównoleglania nic nie wyszło bo liczysz sumę PO zakończeniu procesu dziecka.
Więc może liczyć równolegle a tylko wypisywać PO zakończeniu procesu dziecka?

2023-05-27 18:13 UTC, dawiffi commented
Poprawa bledow

2023-06-03 13:49 UTC, t0meck-pj approved these changes

2023-06-03 13:49 UTC, t0meck-pj commented on s29608-DawidFrontczak/zajecia5/zad6_odczyt.txt
> +		while (fgets(wiadomosc, sizeof(wiadomosc), plik)) {
Czytasz plik bez sprawdzania czy się otworzył

2023-06-03 13:49 UTC, t0meck-pj commented on s29608-DawidFrontczak/zajecia5/zad6_wysylanie.txt
> +		fputs(wiadomosc, plik);
Zapisujesz plik bez sprawdzenia czy się otworzył.

2023-06-03 13:49 UTC, merged

2023-06-03 13:51 UTC, dawiffi commented on s29608-DawidFrontczak/pamietnik.txt
> +na jakim poziomie jest to wszystko prowadzone. Dla osoby nie pracujacej juz w tym zawodzie, i zaczynajacej od zera, jest to abstrakcja.
Jakos sie udalo, byla chwila zalamania zmieszana z naciskiem w pracy 😃