Rozwiązania zadań z 5 zjazdu (procesy)
t0meck-pj/sop2022-23_26c pull request #55
Opened 2023-05-21 10:36 UTC by s27459-pj

Program `tree.c` jest prostą implementacją czegoś na wzór `pstree`. Korzystam tam z `popen` i `pgrep` żeby znaleźć dzieci każdego procesu w drzewie.

Chat w zadaniu 5 jest bardzo prymitywny, bo czyta przychodzące wiadomości dopiero po wysłaniu naszej własnej. Teoretycznie ilość uczestników jest nielimitowana, ale nie mamy żadnego odróżnienia kto wysyła daną wiadomość - wszystko, czego nie wysłał aktualny klient jest traktowany jako wiadomość od "kogoś innego".

2023-06-03 09:04 UTC, t0meck-pj requested changes
Proszę poprawić błędy.

2023-06-03 09:04 UTC, t0meck-pj commented on s27459-StefanKarczewski/zajecia5/zadanie5.c
> +    return 0;
Czego nie robisz przed końcem programu?

2023-06-03 09:14 UTC, s27459-pj commented on s27459-StefanKarczewski/zajecia4/io_1.c
> +    free(file);
To był bug, który naprawiłem w #41. Zmergowałem mastera w tego brancha, więc bugi z poprzedniego zjazdu powinny być już naprawione.

2023-10-01 18:39 UTC, t0meck-pj approved these changes

2023-10-01 18:39 UTC, merged